/*
 * This source file was generated by the Gradle 'init' task
 */
package se.premex.gmai.plugin

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull
import se.premex.gmai.plugin.extensions.ManagedAiExtension

/**
 * A simple unit test for the 'se.premex.gmai' plugin.
 */
class GradleManagedAiPluginTest {
    @Test fun `plugin registers extension`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("se.premex.gmai")

        // Verify the extension is registered
        assertNotNull(project.extensions.findByName("managedAi"))

        // Verify we can access the extension
        val managedAi = project.extensions.getByType(ManagedAiExtension::class.java)
        assertNotNull(managedAi)
    }

    @Test fun `plugin configures extension with defaults`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("se.premex.gmai")

        // Get the extension and verify defaults
        val managedAi = project.extensions.getByType(ManagedAiExtension::class.java)
        assertNotNull(managedAi.ollama)
        assertNotNull(managedAi.models)
    }
}
