name: Cross-Platform Tests

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-cross-platform:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      pull-requests: write
      checks: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true

      - name: Run plugin tests (Unix)
        if: runner.os != 'Windows'
        run: ./gradlew :plugin:check

      - name: Run plugin tests (Windows)
        if: runner.os == 'Windows'
        run: .\gradlew.bat :plugin:check

      - name: Build plugin (Unix)
        if: runner.os != 'Windows'
        run: ./gradlew :plugin:build

      - name: Build plugin (Windows)
        if: runner.os == 'Windows'
        run: .\gradlew.bat :plugin:build

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ matrix.os }}
          path: |
            plugin/build/reports/tests/
            plugin/build/test-results/

      - name: Upload build reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-reports-${{ matrix.os }}
          path: |
            plugin/build/reports/
            build/reports/